# This workflow will build a golang project and create a release
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build and Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -o ttrackerclient ./timetracker/src/client/client.go
      working-directory: <root>/timetracker/src/client

    - name: Build Daemon
      run: go build -o ttrackerd ./timetracker/src/daemon/daemon.go
      working-directory: <root>/timetracker/src/daemon

    - name: Test
      run: go test -v ./...

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          ttrackerclient
          ttrackerd

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: binaries
        path: <root>/bin

    - name: Create Release
      run: |
        version=$(git describe --tags --abbrev=0)
        gh release create "$version" <root>/bin/ttrackerclient -t "Release $version" -n "ttrackerclient $version"
        gh release upload "$version" <root>/bin/ttrackerd -n "ttrackerd $version"
